# Generated by Django 2.1.2 on 2018-10-30 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('logo', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('watched', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('song_title', models.CharField(max_length=64, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Album')),
            ],
        ),
    ]
