# Generated by Django 2.1.2 on 2018-11-01 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20181101_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('video_id', 'album')},
        ),
    ]
