# Generated by Django 2.1.2 on 2018-11-02 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20181101_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_related', to='recommend.Album'),
        ),
    ]
