# Generated by Django 2.1.2 on 2018-11-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20181102_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.FileField(default=None, upload_to='user_img'),
        ),
    ]
