# Generated by Django 2.1.2 on 2018-11-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20181102_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.FileField(default='images/user.png', upload_to='user_img'),
        ),
    ]
