# Generated by Django 2.1.2 on 2018-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20181102_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.FileField(blank=True, null=True, upload_to='user_img'),
        ),
    ]
